apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o83w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-o83w@sha256:73b0b09430cb4a20a5e925d1cedb8a030f7df47dc736de500383d7d34b37035b
        name: my-nodejs
        resources: {}
status: {}
